name: main

on: push

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build postgresql
        run: docker-compose up -d postgres

#     Here must be 20 secs delay for postgres initialization, but server image building spends more time

      - name: Build and run all containers postgresql
        run: docker-compose up -d

      - name: Check that server is running
        run: curl -f -LI http://localhost:8080
