name: main

on: push

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build postgresql
        run: docker-compose up -d postgres

      - name: Wait for postgresql initialization
        uses: whatnick/wait-action@master
        with:
          time: '30s'

      - name: Build and run all containers postgresql
        run: docker-compose up -d
